# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IG0L3O4yFxba35fn-ISEZU9sL60dz32A
"""

from fastapi import FastAPI

from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import pickle
import json

app = FastAPI()
origins = ["*"]

app.add_middleware(
    CORSMiddleware,
    allow_origins = origins,
    allow_credential = True,
    allow_methods = ["*"],
    allow_headers = ["*"]
)

class model_input(BaseModel):
   Company : str
   Type : str
   RAM : int
   Weight : float
   Ips : int
   PPI : float
   CPU_Brand : str
   HDD : int
   SSD : int
   Gpu_Brand : str
   MDVPAPQ : float
   OS : str
# loading the saved model
my_model = pickle.load(open('model.sav','rb'))


@app.post('/')
def parkinsons_pred(input_parameters : model_input):

    cmp = input_dictionary['Company']
    type = input_dictionary['Type']
    ram = input_dictionary['RAM']
    wgt = input_dictionary['Weight']
    ips = input_dictionary['Ips']
    ppi = input_dictionary['PPI']
    cpu = input_dictionary['CPU_Brand']
    hdd = input_dictionary['HDD']
    ssd = input_dictionary['SSD']
    gpu = input_dictionary['Gpu_Brand']
    os = input_dictionary['OS']
    
    input_data = input_parameters.json()
    input_dictionary = json.loads(input_data)

    

    input_list = [cmp, type, ram, wgt, ips, ppi, cpu, hdd, ssd, gpu, os]

    prediction = my_model([input_list])

    return prediction
